[('2070541290', 'Harry Potter - Tome 2 : Harry potter et la chambre', 2, "Cette deuxième aventure d'Harry P
  otter mêle avec génie humour, mystère et frisson. L'intrigue savamment ficelée et pleine de rebondisseme
  nts inattendus envoûte littéralement le lecteur de la première à la dernière page. Un régal !", 10.0, '0000-00-00', 'h
  ors stock', 'Fantastique', 'Grand Format', 22.5, '12, place des clercs 26000 Valence', 'Gallimard'), ('2070543587', 'Harry Pot
  ter - Tome 4 : Harry potter et la coupe d', 2, "Après un horrible été chez les Dursley, Harry Potter entre en quatrième année au
    collège de Poudlard. À quatorze ans, il voudrait simplement être un jeune sorcier comme les autres, retrouver ses amis Ron e
    t Hermione, assister avec eux à la Coupe du Monde de Quidditch, apprendre de nouveaux sortilèges et essayer des potions inconn
    ues. Une grande nouvelle l'attend à son arrivée : la tenue à Poudlard d'un tournoi de magie entre les plus célèbres écoles de sorcellerie. Déjà
      les spectaculaires délégations étrangères font leur entrée... Harry se réjouit. Trop vite. Il va se trouver plongé au coeur des événements les pl
      us dramatiques qu'il ait jamais eu à affronter.\nEnvoûtant, drôle, bouleversant, ce quatrième tome est le pilier central des aventures de Harry Po
      tter.", 10.0, '0000-00-00', 'disponible', 'Fantastique', 'Grand Format', 14.5, 'Place Charles de Gaulle à Chabeuil (Drôme)', 'Gallimard'), ('207055685
      9', "Harry Potter - Tome 5 : Harry potter et l'ordre du", 2, "À quinze ans, Harry entre en cinquième année à Poudlard, mais il n'a jamais été si 
      anxieux. L'adolescence, la perspective des examens et ces étranges cauchemars... Car Celui-Dont-On-Ne-Doit-Pas-Prononcer-Le-Nom est de 
      retour. Le ministère de la Magie semble ne pas prendre cette menace au sérieux, contrairement à Dumbledore. La résistance s'organise alors aut
      our de Harry qui va devoir compter sur le courage et la fidélité de ses amis de toujours... ", 10.0, '0000-00-00', 'disponible', 'Fantastique', 'Grand
        Format', 12.99, 'Place Charles de Gaulle à Chabeuil (Drôme)', 'Gallimard'), ('2070572676', 'Harry Potter - Tome 6 : Harry potter et le prince ', 2, "
        Harry, Ron et Hermione entrent en sixième année à Poudlard où ils vont vivre leur dernière année avant la majorité qui est fixée, chez les sorciers
        , à l'âge de dix-sept ans. Des événements particulièrement marquants vont contribuer à faire passer Harry du
          statut d'adolescent à celui d'homme. Ce tome, sur fond de guerre contre un Voldemort plus puissant que jamais, se
            révèle plus sombre que les précédents. Secrets, alliances et trahisons conduisent aux événements les plus dramatiq
            ues qu'Harry ait eu à affronter. Mais, en... ", 10.0, '0000-00-00', 'disponible', 'Fantastique', 'Grand Format', 10.99, '3
            1 rue Madier de Montjau\n26000 Valence', 'Gallimard'), ('2070615367', 'Harry Potter - Tome 7 : Harry potter et les r
            eliqu', 2, "«Envers et contre tout» est une caractéristique-clé chez J.K. Rowling. Paradoxalement, c'est lorsqu'elle a 
            
            continué à écrire avec une énergie, une passion, un engagement inentamés, en particulier à partir du tome 4 - alors qu'elle était devenue l'une des femmes les plus célèbres et riches au monde, et que chaque suite était attendue par des dizaines de millions de lecteurs du monde entier - , qu'elle force le plus l'admiration. Elle accomplit la mission qu'elle s'est donnée sans faillir, sans jamais décevoir.\nL'ambition de... ", 10.0, datetime.date(2007, 10, 27), 'emprunté', 'Fantastique', 'Grand Format', 15.99, '17, avenue Victor-Hugo Centre commercial Victor-Hugo - 26000  Valence\n\n', 'Gallimard'), ('2070624544', "Harry Potter - : Harry Potter et le prisonnier d'A", 2, "Harry Potter a treize ans. Après des vacances insupportables chez les horribles Dursley, il retrouve ses fidèles amis, Ron et Hermione, pour prendre le train qui les ramène au collège Poudlard. Le monde des gens ordinaires, les Moldus, comme celui des sorciers, est en émoi : aux dernières nouvelles, Sirius Black, un dangereux criminel proche de Voldemort, s'est échappé de la prison d'Azkaban. Les redoutables gardiens de la prison assureront la sécurité du collège Poudlard, car le prisonnier évadé recherche Harry Potter, responsable de l'élimination de son maître. C'est donc sous bonne garde que l'apprenti sorcier fait sa troisième rentrée. Au programme : des cours de divination, la fabrication d'une potion de ratatinage, le dressage des hippogriffes... Mais Harry est-il vraiment à l'abri du danger qui le menace ?", 10.0, datetime.date(1999, 10, 19), 'emprunté', 'Fantastique', 'Grand Format', 9.99, '17, avenue Victor-Hugo Centre commercial Victor-Hugo - 26000  Valence\n\n', 'Gallimard'), ('9782070518425', "Harry Potter, tome 1 : Harry Potter à l'école des ", 2, "Pour et Mrs Dursley, qui habitaient au 4, Privet Drive, avaient toujours affirmé avec la plus grande fierté qu'ils étaient parfaitement nor\xadmaux, merci pour eux. Jamais quiconque n'aurait imaginé qu'ils puissent se trouver impliqués dans quoi que ce soit d'étrange ou de mystérieux. Ils n'avaient pas de temps à perdre avec des sornettes.", 10.0, '0000-00-00', 'emp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               runté', 'Fantastique', 'Poche', 10.99, '12, place des clercs 26000 Valence', 'Gallimard')]